### ISSUE TITLE
Recurring events duplicated on the first instance

### ISSUE THREAD

**Issue by zakkolar** [muness/obsidian-ics#12]
Recurring events seem to get pulled in multiple times when you import events the first day they appear in your calendar. They show up once as a single event, and then get repeated one or more times with "(recurring)" at the end. It doesn't seem to be an issue after the first occurrence.

```
- [ ] 08:25 📅 Important meeting
- [ ] 08:25 📅 Important meeting (recurring)
- [ ] 08:50 📅 A less important meeting
- [ ] 10:30 📅 Brunch
- [ ] 12:00 📅 Get together
- [ ] 12:00 📅 Get together (recurring)
- [ ] 12:00 📅 Get together (recurring)
- [ ] 12:50 📅 Late lunch (recurring)
```

**Comment by muness** [comment]
Thanks for the report. I'll take a look.

**Comment by muness** [comment]
@zakkolar - can you try out [https://github.com/muness/obsidian-ics/releases/tag/0.9.9](0.9.9) to check if this is fixed? Thank you!

**Comment by zakkolar** [comment]
Yes, this looks good - thank you!

It looks like the first occurrence doesn't have the "(recurring)" label after it. That's fine for my purposes, but just pointing it out since I noticed!

**Comment by muness** [comment]
Thank you for spot checking it!

I did that on purpose. Do you think it should indicate that it's recurring?

I am trying to add an indicator attribute for recurring on the event (rather than munging the title) and then let users decide how they want recurring events to be labeled in the formatting markup (TBD).
