### ISSUE TITLE
FR: Support checkboxes OR bullets

### ISSUE THREAD

**Issue by muness** [muness/obsidian-ics#67]
Per calendar, it'd be nice if the items can be checkboxes OR bullets supporting task calendars vs. event calendars.

**Comment by moaschulz** [comment]
I'm completely clueless as to how bothersome this would be to implement or whether there are existing workarounds, but I'd love the imported items to follow a customisable template. Instead of having the toggles in the calendar setup for summary, location, etc., you could just have a prompt where users could enter something like: `- [ ] {{startTime}} {{summary}} ({{location}})`

Anyways, thanks for your work on for the plugin! 🙏

**Comment by muness** [comment]
Added in 1.1.5. Check the per calendar settings.

**Comment by muness** [comment]
Started as discussion #65  (but I then couldn't remember where the request came from until this morning)

**Comment by Rhydderch** [comment]
Thank you for adding this feature!
Do you think it would be possible to extend this feature by supporting custom checkboxes statuses?
In this way I could use the existing checkbox icons to distinguish between different types of calendars. However, this is more a UI thing than really a desperate UX need 😅
<img width="226" alt="image" src="https://github.com/muness/obsidian-ics/assets/3197629/99e5faeb-af17-4733-a6ea-aa09d52bb490">
